sonar.projectKey=ACEest_Fitness_Gym
sonar.projectName=ACEest Fitness Gym
sonar.projectVersion=0.1.0
sonar.sources=.
sonar.tests=test_app.py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/venv/**,**/.git/**,**/__pycache__/**,**/*.db,**/*.db-journal,**/.pytest_cache/**
